### ISSUE TITLE
Question about OAuth2

### ISSUE THREAD

**Issue by Ezyweb-uk** [Makewebbetter/enhanced-woocommerce-mautic-integration#4]
Looks like a great plugin! I notice you're using OAuth2 where as other plugins often use OAuth1. How does this plugin manage token expiry and avoid the user being presented with a Mautic login screen on token expiry?

I see there is a refresh token function `mautic_woo_refresh_token` but what happens when the refresh token lifetime expires and the plugin needs reauthorising?

**Comment by ced-mohitp** [comment]
@Ezyweb-uk  Whenever the connection is broken for any reason, the plugin shows a notification on the wp-admin panel to reauthorize. We usually recommend users set the token lifetime high so that it doesn't need to re-authorized frequently.  
But yes, this is a drawback of using OAuth2. Please let us know if you have any suggestions for that.
